version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - ../:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/ocra_dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"

  postgres:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - POSTGRES_DB=ocra_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: